name: OpenPyStruct
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pre-commit==3.3.2
  - numpy
  - pytorch
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - openseespy
